apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    app: test
    role: backend
    env: development
spec:
  containers:
  - name: test-container
    image: myssh
    imagePullPolicy: Never 
    command: ["/bin/sh", "-c"]
    args:
      - |
        service ssh start && \
        tail -f /dev/null


    ports:
      - containerPort: 5432
    resources:
      requests:
        memory: "256Mi"
        cpu: "500m"
      limits:
        memory: "512Mi"
        cpu: "1"
    env:
      - name: POSTGRES_DB
        value: "postgres"
      - name: POSTGRES_USER
        value: "postgres"
      - name: POSTGRES_PASSWORD
        value: "0000"
---
apiVersion: v1
kind: Service
metadata:
  name: test-svc
  labels:
    app: test
spec:

  selector:
    app: test
    role: backend
    env: development
  type: NodePort
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
      nodePort: 30007